add exit_code for conclusion

diff --git a/.github/workflows/00_pull-request-entry-point.yml b/.github/workflows/00_pull-request-entry-point.yml
--- a/.github/workflows/00_pull-request-entry-point.yml
+++ b/.github/workflows/00_pull-request-entry-point.yml
@@ -109,7 +109,17 @@ jobs:
     needs: [ test-go-projects, e2e-tests ]
     if: ${{ always() }}
     runs-on: [ self-hosted, small ]
+    env:
+      GO_TESTS_RESULT: ${{ needs.test-go-projects.result }}
+      E2E_TESTS_RESULT: ${{ needs.e2e-tests.result }}
     steps:
       - name: Print final message
         run: |
           echo Thats it.
+          echo "We can add here labels to PR to make it visible if any parts are failing"
+      - name: Conclusion
+        run: |
+          exit_code=0
+          if [ "${GO_TESTS_RESULT}" != "success" ]; then exit_code=$(( exit_code + 1 )); fi
+          if [ "${E2E_TESTS_RESULT}" != "success" ]; then exit_code=$(( exit_code + 2 )); fi
+          exit "${exit_code}"
